### ISSUE TITLE
Installation: Cannot render an image using render engine "Mitsuba"

### ISSUE THREAD

**Issue by chenbixuan2017** [mitsuba-renderer/mitsuba-blender#74] opened 2023-08-29 08:22 UTC
Hi! I have followed the steps of mitsuba-blender installation in Wiki "Installation & Update Guide": Download the archives "mitsuba-blender.zip", Install Add-on, click on "Install the dependencies with pip"... 
everything looks the same with the captions in the guide.
(It is my first time doing this, so I do not have other versions of the add-on)
Blender version: v3.4

In Blender, when I switched from Cycles to Mitsuba in the Render Engine bar to render an image, no image came out but a chessboard texture, which means nothing was rendered. But everything was okay when using Cycles or other engines like Eevee, etc.

Maybe I need some additional configurations to do, except for the things mentioned in the Wiki guide? (e.g. specify a Mitsuba executable in somewhere?)
Does anyone know what I should do?
Thanks!
![p1](https://github.com/mitsuba-renderer/mitsuba-blender/assets/131812599/79d5225d-7d85-4693-bf69-1f669099da38)
![p2](https://github.com/mitsuba-renderer/mitsuba-blender/assets/131812599/8bf67b38-409d-45c6-a8cd-f0faa66a1761)
![p3](https://github.com/mitsuba-renderer/mitsuba-blender/assets/131812599/878eb1c6-aa5e-4a1a-820c-ebd20a660ef7)

**Comment by bathal1** [comment] 2023-08-29 08:25
This is a duplicate of #73, which is itself a duplicate of #69, so I'm closing this. Please refer to the previous issues.

**Closed by bathal1** 2023-08-29 08:25 UTC
Labels: bug
