### ISSUE TITLE
<Cannot install dependencies using pip>: <Bug Summary>

### ISSUE THREAD

**Issue by AbdolvakilFazli** [mitsuba-renderer/mitsuba-blender#65] opened 2023-06-12 15:28 UTC
I simply cannot install dependencies using pip. 
Also tried but now I don't know what to do:
ImportError: The 'mitsuba' native modules could not be imported. you're likely to use Mitsuba within a python bi...

**Comment by AbdolvakilFazli** [comment] 2023-06-12 16:35
I am using Blender 3.5 on Windows 10

**Comment by bathal1** [comment] 2023-06-12 16:38
There has been a breaking change in blender 3.5 with Windows for this addon regarding importing mitsuba, which i haven't tracked down yet. Please se my answer [here](https://github.com/mitsuba-renderer/mitsuba-blender/issues/61#issuecomment-1523567811). I will close this issue as it is a duplicate of #61

**Closed by bathal1** 2023-06-12 16:38 UTC
Labels: bug

**Comment by AbdolvakilFazli** [comment] 2023-06-12 17:05
okay , well thanks but how can I lunch blender using this --python-use-system-env flag? I'm using win 10

**Comment by bathal1** [comment] 2023-06-13 07:15
Find the path to your blender executable, open a windows command prompt, and run `<path_to_blender.exe> --python-use-system-env-flag>`
