### ISSUE TITLE
SceneConverter.scene_to_dict() missing 1 required positional argument:  'window_manager'

### ISSUE THREAD

**Issue by Spirou4D** [mitsuba-renderer/mitsuba-blender#71] opened 2023-08-21 07:28 UTC
`Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\mitsuba-blender\engine\final.py", line 42, in render
    self.converter.scene_to_dict(depsgraph)
TypeError: SceneConverter.scene_to_dict() missing 1 required positional argument: 'window_manager'`

**Bug Description**
I installed the 3.3.0 Blender and the last addon for Blender.
Installed the Mitsuba pip module
and activated the addon, then re-run Blender.
I make a cube, saved the blend file and run F12 to render the view
BUT nothing in Render viewport !
and obtained this traceback in terminal windows!

**Environment :**
 - OS:  Windows 10
 - Blender Version: v3.3.0
 - Add-on Version: v0.1 alpha

**Comment by bathal1** [comment] 2023-08-21 08:02
Duplicate of #69, closing.

**Closed by bathal1** 2023-08-21 08:02 UTC
Labels: bug
